### PR TITLE
Rename img-aspect-ratio-lazy.tentative.html to match WPT

### PR DESCRIPTION
**Pull request by foolip**
https://github.com/web-platform-tests/wpt/pull/31805

### CODE REVIEW

**Comment by foolip** [comment]
@KyleJu the tests are failing here because the new name isn't in the manifest yet. What's the process for updating the manifest, and can it be triggered manually?

**Comment by foolip** [comment]
I found the workflow and triggered https://github.com/web-platform-tests/wpt-metadata/actions/runs/1525811905

**Comment by KyleJu** [comment]
This is already renamed by the workflow in #2226

**Comment by foolip** [comment]
Thanks @KyleJu, brilliant!  I forgot the automatic renaming 😬

**Pull request closed without merging**
