### PR TITLE
Upgrade github-script

### PR DESCRIPTION
**Pull request by KyleJu**
Relate to  #6917. Upgrade [Artifact actions v4](https://github.com/actions/download-artifact). v3 will be deprecated by December 5, 2024

### CODE REVIEW

**Comment by jcscottiii** [comment]
One thing I see that's different in v7 is the fact that it uses `github.rest.` instead `github.` for the prefix. That may affect this too.

**Comment by KyleJu** [comment]
Similar error as before:
``` ownloading artifacts
RequestError [HttpError]: ﻿<?xml version="1.0" encoding="utf-8"?>
<Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:362c0930-901e-00e5-3611-[32](https://github.com/web-platform-tests/wpt-metadata/actions/runs/11748079644/job/32731390035#step:2:33)d916000000
Time:2024-11-08T19:08:16.9222017Z</Message></Error>
    at /home/runner/work/_actions/actions/github-script/v3.1.0/dist/index.js:2137:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v3.1.0/dist/index.js:5368:16), <anonymous>:14:16)
    at async main (/home/runner/work/_actions/actions/github-script/v3.1.0/dist/index.js:5394:20) {
  status: 403,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'Content-Length,Content-Type,Date,Server,x-ms-request-id',
    'content-length': '321',
    'content-type': 'application/xml',
    date: 'Fri, 08 Nov 2024 19:08:16 GMT',
    server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
    'x-ms-request-id': '[36](https://github.com/web-platform-tests/wpt-metadata/actions/runs/11748079644/job/32731390035#step:2:37)2c0930-901e-00e5-3611-32d916000000'
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/web-platform-tests/wpt-metadata/actions/artifacts/2164725286/zip',
    headers: {
      accept: 'application/vnd.github.-preview+json',
      'user-agent': 'actions/github-script octokit-core.js/3.2.1 Node.js/20.13.1 (linux; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { agent: [Agent], hook: [Function: bound bound register] }
  }
}
Error: Unhandled error: HttpError: ﻿<?xml version="1.0" encoding="utf-8"?>
<Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:362c0930-901e-00e5-3611-32d916000000
Time:2024-11-08T19:08:16.9222017Z</Message></Error>
```

**Comment by jcscottiii** [comment]
One more thing to try: Change this from v3 to v4:
https://github.com/web-platform-tests/wpt-metadata/blob/45bb84867d55fc0fdbb4bc4cede9124557e0e078/.github/workflows/auto-approve.yml#L59

**Comment by jcscottiii** [comment]
Ignore that one comment. It doesn't even get to that part. Let's keep this PR open. And we can proceed with #6917 for now

**Comment by jcscottiii** [comment]
Additionally, you may want to take a look some of these issues:
- https://github.com/actions/download-artifact/issues/290#issuecomment-1935024240
- https://github.com/actions/upload-artifact/issues/517

The first link shows that it is an issue that other are facing when moving to v4

**Comment by KyleJu** [comment]
I notice that the auto-approve is still running on 3.x on. I don't think the change in this PR is reflected in the workflow on master branch

Screenshot 2024-11-08 11 35 56 AM

**Review by jcscottiii — APPROVED** [review]

**Comment by KyleJu** [comment]
@jcscottiii worked! https://github.com/web-platform-tests/wpt-metadata/pull/6915

**Comment by gsnedders** [comment]
Note we shouldn't need the `actions/github-script` at all, something like https://github.com/web-platform-tests/wpt/blob/e44f4535f4fe673f00e6f487c6240a4c4647b5a6/.github/workflows/check-workflow-run.yml#L32-L37 (note also the `permissions: read` for the token) using `actions/download-artifact` instead.

**Comment by KyleJu** [comment]
> Note we shouldn't need the `actions/github-script` at all, something like https://github.com/web-platform-tests/wpt/blob/e44f4535f4fe673f00e6f487c6240a4c4647b5a6/.github/workflows/check-workflow-run.yml#L32-L37 (note also the `permissions: read` for the token) using `actions/download-artifact` instead.

Filed an issue here,https://github.com/web-platform-tests/wpt-metadata/issues/6935. Thanks!

**Pull request merged**
