### PR TITLE
a11y folder labels

### PR DESCRIPTION
**Pull request by cookiecrook**
straw man PR b/c I'm not sure I understand this part of the docs.

> label is a label to its tests; label is used at a test-level and do not apply to subtests. When label is present in a link:
product should be omitted

What I'm trying to do is apply this label to all tests in this dir, even if they haven't been written yet.

### CODE REVIEW

**Comment by cookiecrook** [comment]
@foolip Is this formatted correctly to apply a label to all current and future tests in a dir? If so, I will add more to accname, wai-aria, etc. and all the other new folders for the interoperability 2323 accessibility investigation

**Comment by cookiecrook** [comment]
Sorry, I missed the `"*"` selector

**Comment by cookiecrook** [comment]
Expecting to see `/graphics-aria` tests here?
https://wpt.fyi/results/?label=master&label=experimental&aligned&q=label%3Aa11y

**Comment by foolip** [comment]
I've filed https://github.com/web-platform-tests/wpt.fyi/issues/3351 for labeling directories and understanding why it doesn't already work.

**Pull request merged**
