### PR TITLE
Remove leading space in crbug.com/1053965 link

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
@stephenmcgruer @KyleJu I didn't track down where this came from, just fix it. But now I see there's another, crbug.com/1008951. And lots of links don't have the leading https:// and thus aren't URLs.

Can we add a lint for valid URLs, perhaps?

**Comment by stephenmcgruer** [comment]
We should trim the strings we receive, but we deliberately don't require `http/https` for them, to minimize the pain for users who are used to typing crbug.com/foo as a link. (We re-add `https` in the wpt.fyi UX)

**Comment by foolip** [comment]
Making URL entry simple is obviously the right priority, but I think we can still ensure we're storing valid URLs, by fixing/completing URLs before submitting them, rather than when retrieving them. This way other code trying to interpret this repo doesn't need to do the same cleanup steps.

**Comment by stephenmcgruer** [comment]
Fair point, seems reasonable.

@Hexcles / @KyleJu - is there any case where we expect this field to not store valid URLs? If not, then Philips suggestion seems like an improvement to me.

**Comment by KyleJu** [comment]
> Fair point, seems reasonable.
> 
> @Hexcles / @KyleJu - is there any case where we expect this field to not store valid URLs? If not, then Philips suggestion seems like an improvement to me.

It should always store valid URLs, either a URL to browser vendors' bug system or a GitHub issue. I will file a bug that adds a lint to GitHub checks

**Pull request merged**
