### PR TITLE
Add terrible script for creating list of bugs from triage metadata

### PR DESCRIPTION
**Pull request by foolip**
Just to show my work. Do not review/merge.

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
(If you delete the branch, will github eventually garbage-collect this?)

**Comment by KyleJu** [comment]
> (If you delete the branch, will github eventually garbage-collect this?)

This as in this PR? No I don't think PRs ever get deleted ever unless you contact them

**Comment by KyleJu** [comment]
In terms of creating list of buts from triage metadata, the easier way might be to use the `api/metadata?` API, https://wpt.fyi/api/metadata?product=safari

**Comment by foolip** [comment]
PR commit history never gets garbage collected. I suspect actually no refs ever get deleted, I once had to contact GitHub support to delete a ref.

**Comment by foolip** [comment]
Ha, https://wpt.fyi/api/metadata?product=safari definitely does most of what what I wrote code for, thanks @KyleJu! Filtering, querying Bugzilla and grouping is still needed, but I can delete some of my code. Is the `status` field the test results, or how can one combine the triage data with test results?

**Comment by KyleJu** [comment]
> Ha, https://wpt.fyi/api/metadata?product=safari definitely does most of what what I wrote code for, thanks @KyleJu! Filtering, querying Bugzilla and grouping is still needed, but I can delete some of my code. Is the `status` field the test results, or how can one combine the triage data with test results?

Correct, the status field is a test result and here is the [explanations ](https://github.com/web-platform-tests/wpt.fyi/blob/master/shared/statuses.go#L38)for this field. In short, you should only see timeout (4) and fail (6). They should be represented in the string format but I forgot the initial rationale behind using the enum format.

**Comment by foolip** [comment]
Aha, so it's the status from the triage data, right, not from current test results?

**Comment by KyleJu** [comment]
> Aha, so it's the status from the triage data, right, not from current test results?

Correct, it's the status from the triage data. By comparing the status from the triage data and current test results, you can figure out if a metadata/URL is out-of-update

**Pull request closed without merging**
