### PR TITLE
Create go.mod for wpt-metadata

### PR DESCRIPTION
**Pull request by KyleJu**
Create go.mod for wpt-metadata. A fix for https://github.com/web-platform-tests/wpt-metadata/issues/58

### CODE REVIEW

**Comment by KyleJu** [comment]
@Hexcles I think it means my GitHub actions setup isn't correct. I will admin merge this PR first.

**Comment by Hexcles** [comment]
Let's try removing this:

https://github.com/web-platform-tests/wpt-metadata/blob/3c980ebc0d048104f4870e2eeb493029733a46c7/.github/workflows/test.yml#L15-L22

**Comment by Hexcles** [comment]
With the use of `go.mod`, we no longer need to put the repo inside `GOPATH`.

**Comment by Hexcles** [comment]
@KyleJu FYI I pushed a commit directly, changing the go version to 1.13 (previously it was 1.11). I think it should work this time.

**Comment by KyleJu** [comment]
> @KyleJu FYI I pushed a commit directly, changing the go version to 1.13 (previously it was 1.11). I think it should work this time.

AHA. Thanks for the help!

**Pull request merged**
