### PR TITLE
Remove interop-2021 label from tentative tests

### PR DESCRIPTION
**Pull request by foolip**
Matches https://github.com/Ecosystem-Infra/wpt-results-analysis/pull/67.

### CODE REVIEW

**Comment by nt1m** [comment]
@foolip Is this something we still want to do?

**Comment by foolip** [comment]
@nt1m I think we should review these tests and decide individually. IIRC I brought this up in a meeting, but we didn't give an action item to anyone so it's just sitting here.

As step 1 I'll rebase this to resolve conflicts.

**Comment by foolip** [comment]
Here are the results of these tests:
https://wpt.fyi/results/css?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=tentative%20and%20%28label%3Ainterop-2021-aspect-ratio%20or%20label%3Ainterop-2021-flexbox%20or%20label%3Ainterop-2021-grid%20or%20label%3Ainterop-2021-position-sticky%20or%20label%3Ainterop-2021-transforms%29

**Comment by foolip** [comment]
So they're actually passing everywhere, making it low priority to figure out if they should be tentative still or not.

If someone would like to remove them an issue on https://github.com/web-platform-tests/interop-2022/issues would be the way to go. These test lists were reviewed when we agreed on Interop 2022, so we shouldn't drop them without discussion.

I'll mark this PR as draft since I'm not planning to do anything with it myself right now.

**Comment by foolip** [comment]
https://github.com/web-platform-tests/results-analysis/pull/66 is the corresponding draft PR for the scoring script. (The Compat 2021 scoring script doesn't use the labels like Interop 2022 does.)

**Pull request closed without merging**
