### PR TITLE
Set up a GitHub Action to automatically merge PRs

### PR DESCRIPTION
**Pull request by Hexcles**
GitHub Action https://github.com/pascalgn/automerge-action, pinned to a
revision which I have roughly reviewed.

Configure it to NOT merge PRs from forks, by which we make sure only PRs
created by people who have write access to the repo can be merged
automatically.

### CODE REVIEW

**Comment by KyleJu** [comment]
So we haven't set a branch protection for `Require pull request reviews before merging` yet. Should  we set it to 1? With the current setup, it will just merge everything that passes the checks

**Comment by Hexcles** [comment]
> So we haven't set a branch protection for Require pull request reviews before merging yet. Should we set it to 1? With the current setup, it will just merge everything that passes the checks

That is intentional. I think we should give everyone who's in the wpt org the power to annotate tests however they want.

**Comment by KyleJu** [comment]
> > So we haven't set a branch protection for Require pull request reviews before merging yet. Should we set it to 1? With the current setup, it will just merge everything that passes the checks
> 
> That is intentional. I think we should give everyone who's in the wpt org the power to annotate tests however they want.

Right but we have been having testing PRs with random values. It would have annoying if they have merged automatically. Also what if we set `MERGE_FILTER_AUTHOR` to @wptfyibot? We don't want to merge PRs that are not related to triage

**Comment by Hexcles** [comment]
Good point! Could you modify the PR in place? I'm afk atm.

**Pull request merged**
