### PR TITLE
add labels for other aria reflection tests

### PR DESCRIPTION
**Pull request by cookiecrook**
Closes https://github.com/web-platform-tests/interop-2023-accessibility-testing/issues/67

### CODE REVIEW

**Comment by cookiecrook** [comment]
@KyleJu please merge when ready. Thanks!

**Comment by KyleJu** [comment]
> @KyleJu please merge when ready. Thanks!

Done!

**Comment by cookiecrook** [comment]
I presume this will show up on https://wpt.fyi/results/html/dom?label=master&label=experimental&aligned&q=label%3Aaccessibility after a follow-up deployment. Is that correct?

**Comment by KyleJu** [comment]
> I presume this will show up on https://wpt.fyi/results/html/dom?label=master&label=experimental&aligned&q=label%3Aaccessibility after a follow-up deployment. Is that correct?

Nope for triage metadata, it should show up within 10 minutes

**Pull request merged**
