### PR TITLE
Add 2 tests to interop-2022-cascade

### PR DESCRIPTION
**Pull request by Loirooriol**
all-prop-revert-layer-noop.html checks `all: revert-layer`.
presentational-hints-rollback.html checks `revert-layer` with preshints.

### CODE REVIEW

**Comment by Loirooriol** [comment]
Should I have tagged [do not merge yet]? I understood this was if I planned to do further changes (which I didn't), so I only assigned reviewer according to the pull request template.

**Comment by foolip** [comment]
@Loirooriol all PRs are merged automatically, so yes you need to add a label to avoid that. Also, for changes to the set of tests in Interop 2022, the group would like to discuss. There's no reason you would have seen it, but the bottom of https://wpt.fyi/interop-2022 says this:

> Please feel free to contribute improvements to [WPT](https://github.com/web-platform-tests/wpt) and then [file an issue](https://github.com/web-platform-tests/interop-2022/issues/new) to request updating the set of tests used for Interop 2022.

I'll put this on the agenda for the Interop 2022 meeting tomorrow, no need to revert this.

**Comment by dholbert** [comment]
Probably not, though I'll defer to @emilio on the tests' appropriateness, since he wrote our cascade layers impl.

**Comment by Loirooriol** [comment]
The tests cover some cases where `revert-layer` was broken in WebKit, so to me they seemed relevant to interop-2022-cascade which is about cascade layers, including `revert-layer`.

**Pull request merged**
